version: 3
projects:
- name: s3-bucket
  dir: terraform-atlantis-demo/s3-bucket
  workflow: terraform
  autoplan:
    when_modified: ["*.tf", "*.tfvars"]
  apply_requirements: ["approved"]

workflows:
  terraform:
    plan:
      steps:
      - init
      - plan
    apply:
      steps:
      - apply